=== Olivier-Heintz/ofbiz-framework/framework/entity/dtd/Informationmodel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:attribute name="entity-name" type="xs:string"/>
<xs:attribute name="package-name" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="value" type="xs:string"/>
<xs:attribute name="attribute" type="xs:string"/>
<xs:attribute name="return" type="xs:string"/>
<xs:attribute name="visibility" type="xs:string"/>
<xs:attribute name="participant1" type="xs:string"/>
<xs:attribute name="participant2" type="xs:string"/>
<xs:attribute name="with" type="xs:string"/>
<xs:attribute name="title" type="xs:string"/>
<xs:attribute name="javaType" type="xs:string"/>
<xs:attribute name="staticValue" type="xs:string"/>

<xs:element name="argument">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="javaType" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="type">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="association" />
        <xs:enumeration value="composite" />
        <xs:enumeration value="aggregate" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="static-attribute">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="staticValue" use="optional"/>
    <!-- <xs:attribute ref="javaType" use="required"/> currently always name=String-->
    <!-- <xs:attribute ref="visibility" use="required"/> currently always public-->
  </xs:complexType>
</xs:element>

<xs:element name="discriminator">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="relation">
  <xs:complexType>
    <xs:attribute ref="with" use="required"/>
    <xs:attribute ref="title" />
    <xs:attribute ref="type" default="association" use="optional" />
  </xs:complexType>
</xs:element>

<xs:element name="method">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="argument"/>
    </xs:sequence>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="return" use="required"/>
    <xs:attribute ref="visibility" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="stereotypeName">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="java-object" />
        <xs:enumeration value="java-pojo-object" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="stereotype">
  <xs:complexType>
    <xs:attribute name="name" use="required">
      <xs:annotation>
        <xs:documentation>show in uml diagram in top of class.
        Used by generator to know what generate :
        A) entity, generating a java object inherit from generic value and automatically load when genericValue is created
        B) view-entity,
        C) inherit, most of time for status and enumeration entity, for a specifics type (status-type or enumeration-type), most of time a view-entity
        D) java-pojo-object, (generator not yet write) generating a simple java object with getter and setter, used by drools fo example</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="entity" />
        <xs:enumeration value="view-entity" />
        <xs:enumeration value="inherit" />
        <xs:enumeration value="java-pojo-object" />
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="class-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="association-class">
  <xs:complexType>
    <xs:attribute ref="participant1" use="required"/>
    <xs:attribute ref="participant2" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="attribute-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
    <xs:attribute ref="attribute" use="required"/>
  </xs:complexType>
</xs:element>

<xs:complexType name="assoc-tag-type" abstract="true"/>

<xs:complexType name="assoc-tag-type-title">
    <xs:complexContent mixed="true">
        <xs:extension base="assoc-tag-type">
                   <xs:attribute ref="name" use="required"/>
                <xs:attribute ref="value" use="required"/>
                <xs:attribute ref="title" use="required"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>



<xs:element name="assoc-tag">
    <xs:complexType>
           <xs:attribute ref="title"/>
           <xs:attribute ref="with"/>
        <xs:attribute ref="name" use="required"/>
           <xs:attribute ref="value" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="entity">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="stereotype"/>
      <xs:element ref="class-tag"/>
      <xs:element ref="static-attribute"/>
      <xs:element ref="attribute-tag"/>
      <xs:element ref="assoc-tag"/>
      <xs:element ref="method"/>
      <xs:element ref="relation"/>
      <xs:element ref="discriminator"/>
      <xs:element ref="association-class"/>
    </xs:choice>
    <xs:attribute ref="entity-name" use="required"/>
    <xs:attribute ref="package-name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="informationmodel">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="entity"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/humanres-informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="Employment" package-name="org.apache.ofbiz.humanres.employment">
    <relation title="To" with="PartyRole" type="composite"/>
    <relation title="From" with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="TerminationReason" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="TerminationType" package-name="org.apache.ofbiz.humanres.employment">
  </entity>

  <entity entity-name="PartyQual" package-name="org.apache.ofbiz.humanres.ability">
    <relation with="Party" type="composite"/>
    <relation with="PartyQualType" type="composite"/>
  </entity>
  <entity entity-name="PartyQualType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="PartyResume" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="PartySkill" package-name="org.apache.ofbiz.humanres.ability">
    <association-class participant2="SkillType" participant1="Party"/>
  </entity>
  <entity entity-name="PerfRatingType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="PerfReview" package-name="org.apache.ofbiz.humanres.ability">
    <relation title="Employee" with="PartyRole" type="composite"/>
  </entity>
  <entity entity-name="PerfReviewItem" package-name="org.apache.ofbiz.humanres.ability">
    <relation with="PerfReview" type="composite"/>
  </entity>
  <entity entity-name="PerfReviewItemType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="PerformanceNote" package-name="org.apache.ofbiz.humanres.ability">
    <relation type="composite" with="PartyRole"/>
  </entity>
  <entity entity-name="PersonTraining" package-name="org.apache.ofbiz.humanres.ability">
    <relation with="Party" type="composite"/>
    <relation with="TrainingClassType" type="composite"/>
  </entity>
  <entity entity-name="ResponsibilityType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="SkillType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="TrainingClassType" package-name="org.apache.ofbiz.humanres.ability">
  </entity>
  <entity entity-name="BenefitType" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="EmploymentApp" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="EmploymentAppSourceType" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="EmplLeave" package-name="org.apache.ofbiz.humanres.employment">
    <relation with="Party" type="composite"/>
    <relation with="EmplLeaveType" type="composite"/>
  </entity>
  <entity entity-name="EmplLeaveType" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="PartyBenefit" package-name="org.apache.ofbiz.humanres.employment">
    <relation title="To" with="PartyRole" type="composite"/>
    <relation title="From" with="PartyRole" type="composite"/>
    <relation with="BenefitType" type="composite"/>
  </entity>
  <entity entity-name="PayGrade" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="PayHistory" package-name="org.apache.ofbiz.humanres.employment">
    <relation with="Employment" type="composite"/>
  </entity>
  <entity entity-name="PayrollPreference" package-name="org.apache.ofbiz.humanres.employment">
    <relation with="Party" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>
  <entity entity-name="SalaryStep" package-name="org.apache.ofbiz.humanres.employment">
    <relation with="PayGrade" type="composite"/>
  </entity>
  <entity entity-name="UnemploymentClaim" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
  <entity entity-name="EmplPosition" package-name="org.apache.ofbiz.humanres.position">
  </entity>
  <entity entity-name="EmplPositionClassType" package-name="org.apache.ofbiz.humanres.position">
  </entity>
  <entity entity-name="EmplPositionFulfillment" package-name="org.apache.ofbiz.humanres.position">
    <association-class participant2="Party" participant1="EmplPosition"/>
  </entity>
  <entity entity-name="EmplPositionReportingStruct" package-name="org.apache.ofbiz.humanres.position">
    <relation title="ReportingTo" with="EmplPosition" type="composite"/>
    <relation title="ManagedBy" with="EmplPosition" type="composite"/>
  </entity>
  <entity entity-name="EmplPositionResponsibility" package-name="org.apache.ofbiz.humanres.position">
    <association-class participant2="ResponsibilityType" participant1="EmplPosition"/>
  </entity>
  <entity entity-name="EmplPositionType" package-name="org.apache.ofbiz.humanres.position">
  </entity>
  <entity entity-name="EmplPositionTypeClass" package-name="org.apache.ofbiz.humanres.position">
    <association-class participant2="EmplPositionClassType" participant1="EmplPositionType"/>
  </entity>
  <entity entity-name="ValidResponsibility" package-name="org.apache.ofbiz.humanres.position">
    <association-class participant2="ResponsibilityType" participant1="EmplPositionType"/>
  </entity>
  <entity entity-name="EmplPositionTypeRate" package-name="org.apache.ofbiz.humanres.position">
    <association-class participant1="EmplPositionType" participant2="RateType"/>
  </entity>
  <entity entity-name="JobRequisition" package-name="org.apache.ofbiz.humanres.recruitment">
  </entity>
  <entity entity-name="JobInterview" package-name="org.apache.ofbiz.humanres.recruitment">
  </entity>
  <entity entity-name="JobInterviewType" package-name="org.apache.ofbiz.humanres.recruitment">
  </entity>
  <entity entity-name="TrainingRequest" package-name="org.apache.ofbiz.humanres.trainings">
  </entity>
  <entity entity-name="EmplLeaveReasonType" package-name="org.apache.ofbiz.humanres.employment">
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/workeffort-informationmodel_ufo.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="TimesheetStatus" package-name="org.apache.ofbiz.workeffort.timesheet" >
     <stereotype name="inherit"/>
     <discriminator name="statusTypeId"/>
     <class-tag name="shortName" value="TIMESHEET_STATUS"/>
     <static-attribute name="IN_PROCESS" staticValue="TIMESHEET_IN_PROCESS" />
     <static-attribute name="COMPLETED"  staticValue="TIMESHEET_COMPLETED" />
     <static-attribute name="APPROVED"   staticValue="TIMESHEET_APPROVED" />
  </entity>

  <entity entity-name="AssignmentStatus" package-name="org.apache.ofbiz.workeffort.workeffort" >
     <stereotype name="inherit"/>
     <discriminator name="statusTypeId"/>
     <class-tag name="shortName" value="PRTYASGN_STATUS"/>
     <static-attribute name="OFFERED"    staticValue="PRTYASGN_OFFERED"/>
     <static-attribute name="ASSIGNED"   staticValue="PRTYASGN_ASSIGNED"/>
     <static-attribute name="UNASSIGNED" staticValue="PRTYASGN_UNASSIGNED"/>
  </entity>

  <entity entity-name="Expectation" package-name="org.apache.ofbiz.workeffort.workeffort" >
     <stereotype name="inherit"/>
     <discriminator name="enumTypeId"/>
     <class-tag name="shortName" value="WORK_EFF_EXPECT"/>
     <static-attribute name="FYI"       staticValue="WEE_FYI" />      <!-- For Your Information -->
     <static-attribute name="REQUIRE"   staticValue="WEE_REQUIRE"/>   <!-- Involvement Required -->
     <static-attribute name="REQUEST"   staticValue="WEE_REQUEST"/>   <!-- Involvement Requested -->
     <static-attribute name="IMMEDIATE" staticValue="WEE_IMMEDIATE"/> <!-- Immediate Response Requested -->
  </entity>

  <entity entity-name="DelegateReason" package-name="org.apache.ofbiz.workeffort.workeffort" >
     <stereotype name="inherit"/>
     <discriminator name="enumTypeId"/>
     <class-tag name="shortName" value="WORK_EFF_DEL_REAS"/>
     <static-attribute name="NEED_HELP"      staticValue="WEDR_NEED_HELP" />
     <static-attribute name="PART_FINISHED"  staticValue="WEDR_PART_FINISHED" />
     <static-attribute name="WHOLE_FINISHED" staticValue="WEDR_WHOLE_FINISHED" />
  </entity>

  <entity entity-name="AvailabilityStatus" package-name="org.apache.ofbiz.workeffort.workeffort" >
     <stereotype name="inherit"/>
     <discriminator name="statusTypeId"/>
     <class-tag name="shortName" value="WEPA_AVAILABILITY"/>
     <static-attribute name="AVAILABLE" staticValue="WEPA_AV_AVAILABLE" />
     <static-attribute name="BUSY"      staticValue="WEPA_AV_BUSY" />
     <static-attribute name="AWAY"      staticValue="WEPA_AV_AWAY" />
  </entity>

</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/party-informationmodel-ufo.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="EmploymentStatus" package-name="org.apache.ofbiz.party.party" >
     <stereotype name="view-entity"/>
     <stereotype name="inherit"/>
     <discriminator name="enumTypeId"/>
     <class-tag name="shortName" value="EMPLOY_STTS"/>
     <static-attribute   name="FULLTIME" staticValue="EMPS_FULLTIME" />
     <static-attribute   name="PARTTIME" staticValue="EMPS_PARTTIME" />
     <static-attribute   name="SELF"     staticValue="EMPS_SELF" />
     <static-attribute   name="HOUSE"    staticValue="EMPS_HOUSE" />
     <static-attribute   name="RETIRED"  staticValue="EMPS_RETIRED" />
     <static-attribute   name="STUDENT"  staticValue="EMPS_STUDENT" />
     <static-attribute   name="UNEMP"    staticValue="EMPS_UNEMP" />
  </entity>

</informationmodel>

=== Olivier-Heintz/ofbiz-framework/framework/entityext/modeldef/informationmodel.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

    <!-- #Bam# entityext-modeldef -->
    <entity entity-name="EntitySync" package-name="org.apache.ofbiz.entity.synchronization">
    </entity>

    <entity entity-name="EntitySyncHistory" package-name="org.apache.ofbiz.entity.synchronization">
        <relation with="EntitySync" type="composite"/>
    </entity>

    <entity entity-name="EntitySyncRemove" package-name="org.apache.ofbiz.entity.synchronization">
    </entity>

    <entity entity-name="EntitySyncInclude" package-name="org.apache.ofbiz.entity.synchronization">
        <relation with="EntitySync" type="composite"/>
    </entity>

    <entity entity-name="EntitySyncIncludeGroup" package-name="org.apache.ofbiz.entity.synchronization">
        <association-class participant1="EntitySync" participant2="EntityGroup" />
    </entity>

    <entity entity-name="EntityGroup" package-name="org.apache.ofbiz.entity.group">
    </entity>

    <entity entity-name="EntityGroupEntry" package-name="org.apache.ofbiz.entity.group">
        <relation with="EntityGroup" type="composite"/>
    </entity>
    <!-- #Eam# entityext-modeldef -->
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/framework/common/modeldef/informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">


  <entity entity-name="Uom" package-name="org.apache.ofbiz.common.uom">
    <stereotype name="entity" />
  </entity>

  <entity entity-name="Enumeration" package-name="org.apache.ofbiz.common.enumeration" >
    <stereotype name="entity"/>
    <discriminator name="enumTypeId"/>
    <class-tag name="cache" value="true"/>
    <class-tag name="orderBy" value="sequenceId"/>
    <class-tag name="gui" value="drop-down, dd-descriptionOnly"/>
    <attribute-tag attribute="enumId" name="mandatory" value="true"/>
    <attribute-tag attribute="enumId" name="gui" value="idName, indexed"/>
  </entity>

  <entity entity-name="StatusItem" package-name="org.apache.ofbiz.common.status" >
    <stereotype name="entity"/>
    <discriminator name="statusTypeId"/>
    <class-tag name="cache" value="true"/>
    <class-tag name="orderBy" value="sequenceId"/>
    <class-tag name="gui" value="drop-down, dd-descriptionOnly"/>
    <attribute-tag attribute="statusId" name="mandatory" value="true"/>
    <attribute-tag attribute="statusId" name="gui" value="idName, indexed"/>
  </entity>

  <entity entity-name="NoteData" package-name="org.apache.ofbiz.common.note" >
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="DataSource" package-name="org.apache.ofbiz.common.datasource">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="DataSourceType" package-name="org.apache.ofbiz.common.datasource">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="EmailTemplateSetting" package-name="org.apache.ofbiz.common.email">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="EnumerationType" package-name="org.apache.ofbiz.common.enumeration">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="CountryCapital" package-name="org.apache.ofbiz.common.geo">
    <relation with="CountryCode" type="composite"/>
    <assoc-tag with="CountryCode" name="GetterSetter" value="CountryCode0" />
    <attribute-tag attribute="countryCode"    name="gui" value="idName" />
    <attribute-tag attribute="countryCapital" name="gui" value="description" />
  </entity>

  <entity entity-name="CountryCode" package-name="org.apache.ofbiz.common.geo">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="CountryTeleCode" package-name="org.apache.ofbiz.common.geo">
    <relation with="CountryCode" type="composite"/>
    <assoc-tag with="CountryCode" name="GetterSetter" value="CountryCode0" />
  </entity>

  <entity entity-name="Geo" package-name="org.apache.ofbiz.common.geo">
    <stereotype name="entity"/>
  </entity>

  <entity entity-name="GeoAssoc" package-name="org.apache.ofbiz.common.geo">
    <relation with="Geo" type="composite"/>
    <relation with="GeoAssocType" type="composite"/>
  </entity>

  <entity entity-name="GeoAssocType" package-name="org.apache.ofbiz.common.geo">
  </entity>

  <entity entity-name="GeoPoint" package-name="org.apache.ofbiz.common.geo">
  </entity>

  <entity entity-name="GeoType" package-name="org.apache.ofbiz.common.geo">
  </entity>

  <entity entity-name="KeywordThesaurus" package-name="org.apache.ofbiz.common.keyword">
    <relation with="Enumeration" type="composite"/>
  </entity>

  <entity entity-name="StandardLanguage" package-name="org.apache.ofbiz.common.language">
  </entity>

  <entity entity-name="CustomMethod" package-name="org.apache.ofbiz.common.method">
  </entity>

  <entity entity-name="CustomMethodType" package-name="org.apache.ofbiz.common.method">
  </entity>

  <entity entity-name="CustomTimePeriod" package-name="org.apache.ofbiz.common.period">
  </entity>

  <entity entity-name="PeriodType" package-name="org.apache.ofbiz.common.period">
  </entity>

  <entity entity-name="StandardTimePeriod" package-name="org.apache.ofbiz.common.period">
  </entity>

  <entity entity-name="StatusType" package-name="org.apache.ofbiz.common.status">
  </entity>

  <entity entity-name="StatusValidChange" package-name="org.apache.ofbiz.common.status">
    <relation with="StatusItem" title="Main" type="composite"/>
    <relation with="StatusItem" title="To" type="composite"/>
  </entity>

  <entity entity-name="UomConversion" package-name="org.apache.ofbiz.common.uom">
    <relation with="Uom" type="composite"/>
        <relation with="Uom" type="composite"/>
  </entity>

  <entity entity-name="UomConversionDated" package-name="org.apache.ofbiz.common.uom">
    <relation with="Uom" type="composite"/>
    <relation with="Uom" type="composite"/>
  </entity>

  <entity entity-name="UomType" package-name="org.apache.ofbiz.common.uom">
  </entity>

  <entity entity-name="UserPreference" package-name="org.apache.ofbiz.common.user">
  </entity>

  <entity entity-name="UserPrefGroupType" package-name="org.apache.ofbiz.common.user">
  </entity>

  <entity entity-name="VisualThemeSet" package-name="org.apache.ofbiz.common.theme">
  </entity>

  <entity entity-name="VisualTheme" package-name="org.apache.ofbiz.common.theme">
  </entity>

  <entity entity-name="VisualThemeResource" package-name="org.apache.ofbiz.common.theme">
    <association-class participant2="VisualTheme" participant1="Enumeration"/>
  </entity>

  <entity entity-name="PortalPortlet" package-name="org.apache.ofbiz.common.portal">
  </entity>

  <entity entity-name="PortletCategory" package-name="org.apache.ofbiz.common.portal">
  </entity>

  <entity entity-name="PortletPortletCategory" package-name="org.apache.ofbiz.common.portal">
    <association-class participant2="PortalPortlet" participant1="PortletCategory"/>
  </entity>

  <entity entity-name="PortalPage" package-name="org.apache.ofbiz.common.portal">
  </entity>

  <entity entity-name="PortalPageColumn" package-name="org.apache.ofbiz.common.portal">
    <relation with="PortalPage" type="composite"/>
  </entity>

  <entity entity-name="PortalPagePortlet" package-name="org.apache.ofbiz.common.portal">
    <association-class participant2="PortalPage" participant1="PortalPortlet"/>
  </entity>

  <entity entity-name="PortletAttribute" package-name="org.apache.ofbiz.common.portal">
    <relation with="PortalPortlet" type="composite"/>
  </entity>

</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/order-informationmodel-ufo.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="CustRqStatus" package-name="org.apache.ofbiz.order.request" >
     <stereotype name="inherit"/>
     <discriminator name="statusTypeId=CUSTREQ_STTS"/>
     <static-attribute name="DRAFT" staticValue="CRQ_DRAFT" />
     <static-attribute name="SUBMITTED" staticValue="CRQ_SUBMITTED" />
     <static-attribute name="ACCEPTED"  staticValue="CRQ_ACCEPTED" />
     <static-attribute name="REVIEWED"  staticValue="CRQ_REVIEWED" />
     <static-attribute name="PENDING"   staticValue="CRQ_PENDING" />
     <static-attribute name="COMPLETED" staticValue="CRQ_COMPLETED" />
     <static-attribute name="REJECTED"  staticValue="CRQ_REJECTED" />
     <static-attribute name="CANCELLED" staticValue="CRQ_CANCELLED" />
  </entity>

</informationmodel>

=== Olivier-Heintz/ofbiz-framework/framework/service/modeldef/informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">
  <entity entity-name="JobSandbox" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="RecurrenceInfo" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="RecurrenceRule" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="RuntimeData" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="TemporalExpression" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="TemporalExpressionAssoc" package-name="org.apache.ofbiz.service.schedule">
    <stereotype name="java-object"/>
    <relation with="TemporalExpression" type="composite"/>
    <relation with="TemporalExpression" type="composite"/>
  </entity>
  <entity entity-name="ServiceSemaphore" package-name="org.apache.ofbiz.service.semaphore">
    <stereotype name="java-object"/>
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/marketing-informationmodel.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">


  <entity entity-name="ContactList" package-name="org.apache.ofbiz.marketing.contact">
    <assoc-tag name="GetterSetter" value="LastModifiedByUserLogin0" title="LastModifiedBy" with="UserLogin"/>
    <assoc-tag name="GetterSetter" value="CreatedByUserLogin0" title="CreatedBy" with="UserLogin"/>
  </entity>

  <entity entity-name="MarketingCampaign" package-name="org.apache.ofbiz.marketing.campaign">
  </entity>

  <entity entity-name="SegmentGroupClassification" package-name="org.apache.ofbiz.marketing.segment">
    <association-class participant1="SegmentGroup" participant2="PartyClassificationGroup"/>
  </entity>

  <entity entity-name="SegmentGroupGeo" package-name="org.apache.ofbiz.marketing.segment">
    <association-class participant1="SegmentGroup" participant2="Geo"/>
  </entity>

  <entity entity-name="SegmentGroupRole" package-name="org.apache.ofbiz.marketing.segment">
    <association-class participant1="SegmentGroup" participant2="PartyRole"/>
  </entity>

  <!-- ========================================================= -->
  <!-- org.apache.ofbiz.marketing.opportunity -->
  <!-- ========================================================= -->

  <entity entity-name="SalesOpportunity" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesOpportunityHistory" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesOpportunityRole" package-name="org.apache.ofbiz.marketing.opportunity">
    <association-class participant2="PartyRole" participant1="SalesOpportunity"/>
  </entity>

  <entity entity-name="SalesOpportunityStage" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesOpportunityWorkEffort" package-name="org.apache.ofbiz.marketing.opportunity">
    <association-class participant2="WorkEffort" participant1="SalesOpportunity"/>
  </entity>

  <entity entity-name="SalesOpportunityQuote" package-name="org.apache.ofbiz.marketing.opportunity">
    <association-class participant2="Quote" participant1="SalesOpportunity"/>
  </entity>

  <entity entity-name="SalesForecast" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesForecastDetail" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesForecastHistory" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesOpportunityCompetitor" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

  <entity entity-name="SalesOpportunityTrckCode" package-name="org.apache.ofbiz.marketing.opportunity">
  </entity>

</informationmodel>
