=== Olivier-Heintz/ofbiz-framework/framework/entity/dtd/Informationmodel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:attribute name="entity-name" type="xs:string"/>
<xs:attribute name="package-name" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="value" type="xs:string"/>
<xs:attribute name="attribute" type="xs:string"/>
<xs:attribute name="return" type="xs:string"/>
<xs:attribute name="visibility" type="xs:string"/>
<xs:attribute name="participant1" type="xs:string"/>
<xs:attribute name="participant2" type="xs:string"/>
<xs:attribute name="with" type="xs:string"/>
<xs:attribute name="title" type="xs:string"/>
<xs:attribute name="javaType" type="xs:string"/>
<xs:attribute name="staticValue" type="xs:string"/>

<xs:element name="argument">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="javaType" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="type">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="association" />
        <xs:enumeration value="composite" />
        <xs:enumeration value="aggregate" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="static-attribute">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="staticValue" use="optional"/>
    <!-- <xs:attribute ref="javaType" use="required"/> currently always name=String-->
    <!-- <xs:attribute ref="visibility" use="required"/> currently always public-->
  </xs:complexType>
</xs:element>

<xs:element name="discriminator">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="relation">
  <xs:complexType>
    <xs:attribute ref="with" use="required"/>
    <xs:attribute ref="title" />
    <xs:attribute ref="type" default="association" use="optional" />
  </xs:complexType>
</xs:element>

<xs:element name="method">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="argument"/>
    </xs:sequence>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="return" use="required"/>
    <xs:attribute ref="visibility" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="stereotypeName">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="java-object" />
        <xs:enumeration value="java-pojo-object" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="stereotype">
  <xs:complexType>
    <xs:attribute name="name" use="required">
      <xs:annotation>
        <xs:documentation>show in uml diagram in top of class.
        Used by generator to know what generate :
        A) entity, generating a java object inherit from generic value and automatically load when genericValue is created
        B) view-entity,
        C) inherit, most of time for status and enumeration entity, for a specifics type (status-type or enumeration-type), most of time a view-entity
        D) java-pojo-object, (generator not yet write) generating a simple java object with getter and setter, used by drools fo example</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="entity" />
        <xs:enumeration value="view-entity" />
        <xs:enumeration value="inherit" />
        <xs:enumeration value="java-pojo-object" />
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="class-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="association-class">
  <xs:complexType>
    <xs:attribute ref="participant1" use="required"/>
    <xs:attribute ref="participant2" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="attribute-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
    <xs:attribute ref="attribute" use="required"/>
  </xs:complexType>
</xs:element>

<xs:complexType name="assoc-tag-type" abstract="true"/>

<xs:complexType name="assoc-tag-type-title">
    <xs:complexContent mixed="true">
        <xs:extension base="assoc-tag-type">
                   <xs:attribute ref="name" use="required"/>
                <xs:attribute ref="value" use="required"/>
                <xs:attribute ref="title" use="required"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>



<xs:element name="assoc-tag">
    <xs:complexType>
           <xs:attribute ref="title"/>
           <xs:attribute ref="with"/>
        <xs:attribute ref="name" use="required"/>
           <xs:attribute ref="value" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="entity">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="stereotype"/>
      <xs:element ref="class-tag"/>
      <xs:element ref="static-attribute"/>
      <xs:element ref="attribute-tag"/>
      <xs:element ref="assoc-tag"/>
      <xs:element ref="method"/>
      <xs:element ref="relation"/>
      <xs:element ref="discriminator"/>
      <xs:element ref="association-class"/>
    </xs:choice>
    <xs:attribute ref="entity-name" use="required"/>
    <xs:attribute ref="package-name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="informationmodel">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="entity"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Olivier-Heintz/ofbiz-framework/framework/security/modeldef/informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="X509IssuerProvision" package-name="org.apache.ofbiz.security.cert">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="UserLogin" package-name="org.apache.ofbiz.security.login">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="UserLoginPasswordHistory" package-name="org.apache.ofbiz.security.login">
    <stereotype name="java-object"/>
    <relation with="UserLogin" type="composite"/>
  </entity>
  <entity entity-name="UserLoginHistory" package-name="org.apache.ofbiz.security.login">
    <stereotype name="java-object"/>
    <relation with="UserLogin" type="composite"/>
  </entity>
  <entity entity-name="UserLoginSession" package-name="org.apache.ofbiz.security.login">
    <stereotype name="java-object"/>
    <relation with="UserLogin" type="composite"/>
  </entity>
  <entity entity-name="SecurityGroup" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="SecurityGroupPermission" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
    <relation with="SecurityGroup" type="composite"/>
  </entity>
  <entity entity-name="SecurityPermission" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
  </entity>
<!--  <entity entity-name="SecurityPermissionAutoGrant" package-name="org.apache.ofbiz.security.securitygroup">-->
<!--    <stereotype name="java-object"/>-->
<!--    <relation with="SecurityPermission" type="composite"/>-->
<!--  </entity>-->
  <entity entity-name="UserLoginSecurityGroup" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
    <association-class participant2="UserLogin" participant1="SecurityGroup"/>
  </entity>
  <entity entity-name="ProtectedView" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
    <relation with="SecurityGroup" type="composite"/>
  </entity>
  <entity entity-name="TarpittedLoginView" package-name="org.apache.ofbiz.security.securitygroup">
    <stereotype name="java-object"/>
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/workeffort-informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="TimeEntry" package-name="org.apache.ofbiz.workeffort.timesheet">
  </entity>

  <entity entity-name="Timesheet" package-name="org.apache.ofbiz.workeffort.timesheet">
  </entity>

  <entity entity-name="TimesheetRole" package-name="org.apache.ofbiz.workeffort.timesheet">
    <association-class participant1="Timesheet" participant2="PartyRole" />
  </entity>

  <entity entity-name="ApplicationSandbox" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="CommunicationEventWorkEff" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="CommunicationEvent"/>
  </entity>

  <entity entity-name="Deliverable" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="DeliverableType" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffort" package-name="org.apache.ofbiz.workeffort.workeffort">
    <stereotype name="java-object"/>
    <class-tag name="uniqueNameAttribute" value="true"/>
  </entity>

  <entity entity-name="WorkEffortAssoc" package-name="org.apache.ofbiz.workeffort.workeffort">
    <discriminator name="workEffortTypeId"/>
    <stereotype name="java-object"/>
    <relation with="WorkEffortAssocType"     type="composite"/>
    <relation with="WorkEffort" title="From" type="composite"/>
    <relation with="WorkEffort" title="To"   type="composite"/>
  </entity>

  <entity entity-name="WorkEffortAssocAttribute" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffortAssoc" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortAssocType" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffortAssocTypeAttr" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffortAssocType" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortAttribute" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortBilling" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="InvoiceItem"/>
  </entity>

  <entity entity-name="WorkEffortContactMech" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="ContactMech"/>
  </entity>

  <entity entity-name="WorkEffortContent" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
    <relation with="Content" type="composite"/>
    <relation with="WorkEffortContentType" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortContentType" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffortDeliverableProd" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="Deliverable" participant1="WorkEffort"/>
  </entity>

  <entity entity-name="WorkEffortEventReminder" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortFixedAssetAssign" package-name="org.apache.ofbiz.workeffort.workeffort">
    <discriminator name="workEffortTypeId"/>
    <stereotype name="java-object"/>
    <association-class participant2="WorkEffort" participant1="FixedAsset"/>
  </entity>

  <entity entity-name="WorkEffortFixedAssetStd" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="FixedAssetType"/>
  </entity>

  <entity entity-name="WorkEffortGoodStandard" package-name="org.apache.ofbiz.workeffort.workeffort">
    <discriminator name="workEffortTypeId"/>
    <stereotype name="java-object"/>
    <relation with="WorkEffort" type="composite"/>
    <relation with="WorkEffortGoodStandardType" type="composite"/>
    <relation with="Product" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortGoodStandardType" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffortIcalData" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortInventoryAssign" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant1="WorkEffort" participant2="InventoryItem"/>
  </entity>

  <entity entity-name="WorkEffortInventoryProduced" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="InventoryItem"/>
  </entity>

  <entity entity-name="WorkEffortCostCalc" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
    <relation with="CostComponentType" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortKeyword" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortNote" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="NoteData"/>
  </entity>

  <entity entity-name="WorkEffortPartyAssignment" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant1="WorkEffort" participant2="PartyRole"/>
  </entity>

  <entity entity-name="WorkEffortPurposeType" package-name="org.apache.ofbiz.workeffort.workeffort">
    <discriminator name="workEffortTypeId"/>
    <stereotype name="java-object"/>
  </entity>

  <entity entity-name="WorkEffortReview" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
    <relation with="UserLogin" type="composite"/>
    <relation with="StatusItem" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortSearchConstraint" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffortSearchResult" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortSearchResult" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffortSkillStandard" package-name="org.apache.ofbiz.workeffort.workeffort">
    <association-class participant2="WorkEffort" participant1="SkillType"/>
  </entity>

  <entity entity-name="WorkEffortStatus" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
    <relation with="StatusItem" type="composite"/>
    <assoc-tag name="GetterSetter" value="SetByUserLoginO" title="SetBy" with="UserLogin"/>
  </entity>

  <entity entity-name="WorkEffortTransBox" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffort" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortType" package-name="org.apache.ofbiz.workeffort.workeffort">
  </entity>

  <entity entity-name="WorkEffortTypeAttr" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="WorkEffortType" type="composite"/>
  </entity>

  <entity entity-name="WorkEffortSurveyAppl" package-name="org.apache.ofbiz.workeffort.workeffort">
    <relation with="Survey" type="composite"/>
    <relation with="WorkEffort" type="composite"/>
    <relation with="ProductStoreSurveyAppl" type="composite"/>
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/framework/webapp/modeldef/informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="BrowserType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="PlatformType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="ProtocolType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="ServerHit" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
    <relation with="ServerHitType" type="composite"/>
    <relation with="Visit" type="composite"/>
  </entity>
  <entity entity-name="ServerHitBin" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="ServerHitType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="UserAgent" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="UserAgentMethodType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="UserAgentType" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="Visit" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="Visitor" package-name="org.apache.ofbiz.webapp.visit">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="WebPage" package-name="org.apache.ofbiz.webapp.website">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="WebSite" package-name="org.apache.ofbiz.webapp.website">
    <stereotype name="java-object"/>
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/manufacturing-informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="ProductManufacturingRule" package-name="org.apache.ofbiz.manufacturing.bom">
    <assoc-tag name="GetterSetter" value="ProductFeatureO" with="ProductFeature"/>
  </entity>
  <entity entity-name="TechDataCalendar" package-name="org.apache.ofbiz.manufacturing.techdata">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="TechDataCalendarExcDay" package-name="org.apache.ofbiz.manufacturing.techdata">
    <stereotype name="java-object"/>
    <relation with="TechDataCalendar" type="composite"/>
  </entity>
  <entity entity-name="TechDataCalendarExcWeek" package-name="org.apache.ofbiz.manufacturing.techdata">
    <relation with="TechDataCalendar" type="composite"/>
  </entity>
  <entity entity-name="TechDataCalendarWeek" package-name="org.apache.ofbiz.manufacturing.techdata">
    <stereotype name="java-object"/>
  </entity>
  <entity entity-name="MrpEventType" package-name="org.apache.ofbiz.manufacturing.mrp">
  </entity>
  <entity entity-name="MrpEvent" package-name="org.apache.ofbiz.manufacturing.mrp">
    <relation with="Product" type="composite"/>
    <relation with="MrpEventType" type="composite"/>
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/shipment-informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="ItemIssuance" package-name="org.apache.ofbiz.shipment.issuance">
  </entity>

  <entity entity-name="ItemIssuanceRole" package-name="org.apache.ofbiz.shipment.issuance">
    <relation with="ItemIssuance" type="composite"/>
    <relation with="Party" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="Picklist" package-name="org.apache.ofbiz.shipment.picklist">
    <stereotype name="java-object"/>
  </entity>

  <entity entity-name="PicklistBin" package-name="org.apache.ofbiz.shipment.picklist">
  </entity>

  <entity entity-name="PicklistItem" package-name="org.apache.ofbiz.shipment.picklist">
    <relation with="PicklistBin" type="composite"/>
    <relation with="OrderItemShipGroup" type="composite"/>
    <relation with="OrderItem" type="composite"/>
    <relation with="InventoryItem" type="composite"/>
  </entity>

  <entity entity-name="PicklistRole" package-name="org.apache.ofbiz.shipment.picklist">
    <relation with="Picklist" type="composite"/>
    <relation with="PartyRole" type="composite"/>
    <relation with="RoleType" type="composite"/>
    <assoc-tag name="GetterSetter" value="CreatedByUserLoginO" title="CreatedBy" with="UserLogin"/>
    <assoc-tag name="GetterSetter" value="LastModifiedByUserLogino" title="LastModifiedBy" with="UserLogin"/>
  </entity>

  <entity entity-name="PicklistStatusHistory" package-name="org.apache.ofbiz.shipment.picklist">
    <relation with="Picklist" type="composite"/>
  </entity>

  <entity entity-name="RejectionReason" package-name="org.apache.ofbiz.shipment.receipt">
  </entity>

  <entity entity-name="ShipmentReceipt" package-name="org.apache.ofbiz.shipment.receipt">
  </entity>

  <entity entity-name="ShipmentReceiptRole" package-name="org.apache.ofbiz.shipment.receipt">
    <relation with="ShipmentReceipt" type="composite"/>
    <relation with="Party" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="CarrierShipmentMethod" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="ShipmentMethodType" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="CarrierShipmentBoxType" package-name="org.apache.ofbiz.shipment.shipment">
    <association-class participant2="Party" participant1="ShipmentBoxType"/>
  </entity>

  <entity entity-name="Delivery" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="Shipment" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="java-object"/>
  </entity>

  <entity entity-name="ShipmentAttribute" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="Shipment" type="composite"/>
  </entity>

  <entity entity-name="ShipmentBoxType" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentContactMech" package-name="org.apache.ofbiz.shipment.shipment">
    <association-class participant1="Shipment" participant2="ShipmentContactMechType"/>
  </entity>

  <entity entity-name="ShipmentContactMechType" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentCostEstimate" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayConfigType" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayConfig" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayDhl" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayFedex" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayUps" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentGatewayUsps" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentItem" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="java-object"/>
    <relation with="Shipment" type="composite"/>
  </entity>

  <entity entity-name="ShipmentItemBilling" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="ShipmentItem" type="composite"/>
    <relation with="InvoiceItem" type="composite"/>
  </entity>

  <entity entity-name="ShipmentItemFeature" package-name="org.apache.ofbiz.shipment.shipment">
    <association-class participant2="ShipmentItem" participant1="ProductFeature"/>
  </entity>

  <entity entity-name="ShipmentMethodType" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentPackage" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="Shipment" type="composite"/>
  </entity>

  <entity entity-name="ShipmentPackageContent" package-name="org.apache.ofbiz.shipment.shipment">
    <association-class participant1="ShipmentItem" participant2="ShipmentPackage"/>
  </entity>

  <entity entity-name="ShipmentPackageRouteSeg" package-name="org.apache.ofbiz.shipment.shipment">
    <association-class participant2="ShipmentRouteSegment" participant1="ShipmentPackage"/>
  </entity>

  <entity entity-name="ShipmentRouteSegment" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="Shipment" type="composite"/>

  </entity>

  <entity entity-name="ShipmentStatus" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="java-object"/>
    <association-class participant2="Shipment" participant1="StatusItem"/>
    <stereotype name="inherit"/>
    <discriminator name="statusId"/>
    <static-attribute visibility="public" name="INPUT" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="INPUT" value="SHIPMENT_INPUT"/>
    <static-attribute visibility="public" name="SCHEDULED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="SCHEDULED" value="SHIPMENT_SCHEDULED"/>
    <static-attribute visibility="public" name="PICKED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="PICKED" value="SHIPMENT_PICKED"/>
    <static-attribute visibility="public" name="PACKED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="PACKED" value="SHIPMENT_PACKED"/>
    <static-attribute visibility="public" name="SHIPPED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="SHIPPED" value="SHIPMENT_SHIPPED"/>
    <static-attribute visibility="public" name="DELIVERED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="DELIVERED" value="SHIPMENT_DELIVERED"/>
    <static-attribute visibility="public" name="CANCELLED" javaType="java.lang.String"/>
    <attribute-tag name="staticValue" attribute="CANCELLED" value="SHIPMENT_CANCELLED"/>
  </entity>

  <entity entity-name="ShipmentType" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>

  <entity entity-name="ShipmentTypeAttr" package-name="org.apache.ofbiz.shipment.shipment">
    <relation with="ShipmentType" type="composite"/>
  </entity>

  <entity entity-name="ShippingDocument" package-name="org.apache.ofbiz.shipment.shipment">
  </entity>
</informationmodel>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/product-informationmodel_ufo.xml
<?xml version="1.0" encoding="utf-8"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
    xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">

  <entity entity-name="ShipmentGatewayDhl" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="entity"/>
    <discriminator name="shipmentGatewayConfTypeId=SHIP_GATEWAY_DHL" />
  </entity>
  <entity entity-name="ShipmentGatewayFedex" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="entity"/>
    <discriminator name="shipmentGatewayConfTypeId=SHIP_GATEWAY_FEDEX" />
  </entity>
  <entity entity-name="ShipmentGatewayUps" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="entity"/>
    <discriminator name="shipmentGatewayConfTypeId=SHIP_GATEWAY_UPS" />
  </entity>
  <entity entity-name="ShipmentGatewayUsps" package-name="org.apache.ofbiz.shipment.shipment">
    <stereotype name="entity"/>
    <discriminator name="shipmentGatewayConfTypeId=SHIP_GATEWAY_USPS" />
  </entity>
  <entity entity-name="ShippingDocument" package-name="org.apache.ofbiz.shipment.shipment">
    <discriminator name="documentTypeId=SHIPPING_DOCUMENT" />
  </entity>

</informationmodel>
