=== Olivier-Heintz/ofbiz-framework/framework/entity/dtd/Informationmodel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:attribute name="entity-name" type="xs:string"/>
<xs:attribute name="package-name" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="value" type="xs:string"/>
<xs:attribute name="attribute" type="xs:string"/>
<xs:attribute name="return" type="xs:string"/>
<xs:attribute name="visibility" type="xs:string"/>
<xs:attribute name="participant1" type="xs:string"/>
<xs:attribute name="participant2" type="xs:string"/>
<xs:attribute name="with" type="xs:string"/>
<xs:attribute name="title" type="xs:string"/>
<xs:attribute name="javaType" type="xs:string"/>
<xs:attribute name="staticValue" type="xs:string"/>

<xs:element name="argument">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="javaType" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="type">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="association" />
        <xs:enumeration value="composite" />
        <xs:enumeration value="aggregate" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="static-attribute">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="staticValue" use="optional"/>
    <!-- <xs:attribute ref="javaType" use="required"/> currently always name=String-->
    <!-- <xs:attribute ref="visibility" use="required"/> currently always public-->
  </xs:complexType>
</xs:element>

<xs:element name="discriminator">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="relation">
  <xs:complexType>
    <xs:attribute ref="with" use="required"/>
    <xs:attribute ref="title" />
    <xs:attribute ref="type" default="association" use="optional" />
  </xs:complexType>
</xs:element>

<xs:element name="method">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="argument"/>
    </xs:sequence>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="return" use="required"/>
    <xs:attribute ref="visibility" use="required"/>
  </xs:complexType>
</xs:element>

<xs:attribute name="stereotypeName">
  <xs:simpleType>
    <xs:restriction base="xs:string">
        <xs:enumeration value="java-object" />
        <xs:enumeration value="java-pojo-object" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>

<xs:element name="stereotype">
  <xs:complexType>
    <xs:attribute name="name" use="required">
      <xs:annotation>
        <xs:documentation>show in uml diagram in top of class.
        Used by generator to know what generate :
        A) entity, generating a java object inherit from generic value and automatically load when genericValue is created
        B) view-entity,
        C) inherit, most of time for status and enumeration entity, for a specifics type (status-type or enumeration-type), most of time a view-entity
        D) java-pojo-object, (generator not yet write) generating a simple java object with getter and setter, used by drools fo example</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="entity" />
        <xs:enumeration value="view-entity" />
        <xs:enumeration value="inherit" />
        <xs:enumeration value="java-pojo-object" />
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="class-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="association-class">
  <xs:complexType>
    <xs:attribute ref="participant1" use="required"/>
    <xs:attribute ref="participant2" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="attribute-tag">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="value" use="required"/>
    <xs:attribute ref="attribute" use="required"/>
  </xs:complexType>
</xs:element>

<xs:complexType name="assoc-tag-type" abstract="true"/>

<xs:complexType name="assoc-tag-type-title">
    <xs:complexContent mixed="true">
        <xs:extension base="assoc-tag-type">
                   <xs:attribute ref="name" use="required"/>
                <xs:attribute ref="value" use="required"/>
                <xs:attribute ref="title" use="required"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>



<xs:element name="assoc-tag">
    <xs:complexType>
           <xs:attribute ref="title"/>
           <xs:attribute ref="with"/>
        <xs:attribute ref="name" use="required"/>
           <xs:attribute ref="value" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="entity">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="stereotype"/>
      <xs:element ref="class-tag"/>
      <xs:element ref="static-attribute"/>
      <xs:element ref="attribute-tag"/>
      <xs:element ref="assoc-tag"/>
      <xs:element ref="method"/>
      <xs:element ref="relation"/>
      <xs:element ref="discriminator"/>
      <xs:element ref="association-class"/>
    </xs:choice>
    <xs:attribute ref="entity-name" use="required"/>
    <xs:attribute ref="package-name" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="informationmodel">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="entity"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Olivier-Heintz/ofbiz-framework/applications/datamodel/modeldef/content-informationmodel.xml
<?xml version="1.0"?>
<informationmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:xsd="http://www.w3.org/2000/10/XMLSchema"
                   xsi:noNamespaceSchemaLocation="http://repository.ofbizextra.org/dtd/Informationmodel.xsd">


  <entity entity-name="Content" package-name="org.apache.ofbiz.content.content">
    <assoc-tag name="GetterSetter" value="LastModifiedByUserLogin0" title="LastModifiedBy" with="UserLogin"/>
    <assoc-tag name="GetterSetter" value="CreatedByUserLogin0" title="CreatedBy" with="UserLogin"/>
  </entity>
  <entity entity-name="ContentApproval" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentAssoc" package-name="org.apache.ofbiz.content.content">
    <relation with="Content" type="composite" title="From"/>
    <relation with="Content" type="composite" title="To"/>
    <relation with="ContentAssocType" type="composite"/>
    <assoc-tag name="GetterSetter" value="LastModifiedByUserLogin0" title="LastModifiedBy" with="UserLogin"/>
    <assoc-tag name="GetterSetter" value="CreatedByUserLogin0" title="CreatedBy" with="UserLogin"/>
  </entity>

  <entity entity-name="ContentAssocPredicate" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentAssocType" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentAttribute" package-name="org.apache.ofbiz.content.content">
    <relation with="Content" type="composite"/>
  </entity>

  <entity entity-name="ContentMetaData" package-name="org.apache.ofbiz.content.content">
    <association-class participant2="Content" participant1="MetaDataPredicate"/>
  </entity>

  <entity entity-name="ContentOperation" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentPurpose" package-name="org.apache.ofbiz.content.content">
    <association-class participant2="Content" participant1="ContentPurposeType"/>
  </entity>

  <entity entity-name="ContentPurposeOperation" package-name="org.apache.ofbiz.content.content">
    <relation with="ContentPurposeType" type="composite"/>
    <relation with="ContentOperation" type="composite"/>
    <relation with="RoleType" type="composite"/>
    <relation with="StatusItem" type="composite"/>
    <relation with="Enumeration" type="composite"/>
  </entity>

  <entity entity-name="ContentPurposeType" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentRevision" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentRevisionItem" package-name="org.apache.ofbiz.content.content">
    <relation with="ContentRevision" type="composite"/>
  </entity>

  <entity entity-name="ContentRole" package-name="org.apache.ofbiz.content.content">
    <relation with="Content" type="composite"/>
    <relation with="Party" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="ContentType" package-name="org.apache.ofbiz.content.content">
  </entity>

  <entity entity-name="ContentTypeAttr" package-name="org.apache.ofbiz.content.content">
    <relation with="ContentType" type="composite"/>
  </entity>

  <entity entity-name="AudioDataResource" package-name="org.apache.ofbiz.content.data">
    <discriminator name="dataResourceTypeId" />

  </entity>

  <entity entity-name="CharacterSet" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="DataCategory" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="DataResource" package-name="org.apache.ofbiz.content.data">
    <assoc-tag name="GetterSetter" value="LastModifiedByUserLogin0" title="LastModifiedBy" with="UserLogin"/>
    <assoc-tag name="GetterSetter" value="CreatedByUserLogin0" title="CreatedBy" with="UserLogin"/>
  </entity>

  <entity entity-name="DataResourceAttribute" package-name="org.apache.ofbiz.content.data">
    <relation with="DataResource" type="composite"/>
  </entity>

  <entity entity-name="DataResourceMetaData" package-name="org.apache.ofbiz.content.data">
    <relation with="DataResource" type="composite"/>
    <relation with="MetaDataPredicate" type="composite"/>
    <relation with="DataSource" type="composite"/>
  </entity>

  <entity entity-name="DataResourcePurpose" package-name="org.apache.ofbiz.content.data">
    <association-class participant2="DataResource" participant1="ContentPurposeType"/>
    </entity>

  <entity entity-name="DataResourceRole" package-name="org.apache.ofbiz.content.data">
    <relation with="DataResource" type="composite"/>
    <relation with="Party" type="composite"/>
    <relation with="PartyRole" type="composite"/>
  </entity>

  <entity entity-name="DataResourceType" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="DataResourceTypeAttr" package-name="org.apache.ofbiz.content.data">
    <relation with="DataResourceType" type="composite"/>
  </entity>

  <entity entity-name="DataTemplateType" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="ElectronicText" package-name="org.apache.ofbiz.content.data">
    <discriminator name="dataResourceTypeId" />
    <class-tag name="shortName" value="ELECTRONIC_TEXT"/>
  </entity>

  <entity entity-name="FileExtension" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="ImageDataResource" package-name="org.apache.ofbiz.content.data">
    <discriminator name="dataResourceTypeId" />
  </entity>

  <entity entity-name="MetaDataPredicate" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="MimeType" package-name="org.apache.ofbiz.content.data">
  </entity>

  <entity entity-name="MimeTypeHtmlTemplate" package-name="org.apache.ofbiz.content.data">
    <relation with="MimeType" type="composite"/>
  </entity>

  <entity entity-name="OtherDataResource" package-name="org.apache.ofbiz.content.data">
    <discriminator name="dataResourceTypeId" />
  </entity>

  <entity entity-name="VideoDataResource" package-name="org.apache.ofbiz.content.data">
    <discriminator name="dataResourceTypeId" />
  </entity>

  <entity entity-name="Document" package-name="org.apache.ofbiz.content.document">
  </entity>

  <entity entity-name="DocumentAttribute" package-name="org.apache.ofbiz.content.document">
    <relation with="Document" type="composite"/>
  </entity>

  <entity entity-name="DocumentType" package-name="org.apache.ofbiz.content.document">
  </entity>
  <entity entity-name="DocumentTypeAttr" package-name="org.apache.ofbiz.content.document">
    <relation with="DocumentType" type="composite"/>
  </entity>

  <entity entity-name="WebPreferenceType" package-name="org.apache.ofbiz.content.preference">
  </entity>

  <entity entity-name="WebUserPreference" package-name="org.apache.ofbiz.content.preference">
    <relation with="WebPreferenceType" type="composite"/>
    <relation with="UserLogin" type="composite"/>
    <relation with="Party" type="composite"/>
  </entity>

  <entity entity-name="Survey" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyApplType" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyMultiResp" package-name="org.apache.ofbiz.content.survey">
    <relation with="Survey" type="composite"/>
  </entity>

  <entity entity-name="SurveyMultiRespColumn" package-name="org.apache.ofbiz.content.survey">
    <relation with="SurveyMultiResp" type="composite"/>
  </entity>

  <entity entity-name="SurveyPage" package-name="org.apache.ofbiz.content.survey">
    <relation with="Survey" type="composite"/>
  </entity>

  <entity entity-name="SurveyQuestion" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyQuestionAppl" package-name="org.apache.ofbiz.content.survey">
    <association-class participant2="Survey" participant1="SurveyQuestion"/>
  </entity>

  <entity entity-name="SurveyQuestionCategory" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyQuestionOption" package-name="org.apache.ofbiz.content.survey">
    <relation with="SurveyQuestion" type="composite"/>
  </entity>

  <entity entity-name="SurveyQuestionType" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyResponse" package-name="org.apache.ofbiz.content.survey">
  </entity>

  <entity entity-name="SurveyResponseAnswer" package-name="org.apache.ofbiz.content.survey">
    <relation with="SurveyResponse" type="composite"/>
    <relation with="SurveyQuestion" type="composite"/>
  </entity>

  <entity entity-name="SurveyTrigger" package-name="org.apache.ofbiz.content.survey">
    <association-class participant2="Survey" participant1="SurveyApplType"/>
  </entity>

  <entity entity-name="WebSiteContent" package-name="org.apache.ofbiz.content.website">
  </entity>

  <entity entity-name="WebSiteContentType" package-name="org.apache.ofbiz.content.website">
  </entity>

  <entity entity-name="WebSitePathAlias" package-name="org.apache.ofbiz.content.website">
     <relation with="WebSite" type="composite"/>
  </entity>

  <entity entity-name="WebSitePublishPoint" package-name="org.apache.ofbiz.content.website">
    <discriminator name="contentTypeId" />
  </entity>

  <entity entity-name="WebSiteRole" package-name="org.apache.ofbiz.party.party">
    <association-class participant2="PartyRole" participant1="WebSite"/>
  </entity>
</informationmodel>
